name: fintech_workspace

packages:
  - app
  - core
  - features/*

command:
  version:
    branch: main
  bootstrap:
    environment:
      sdk: ">=3.6.0 <4.0.0"
    dev_dependencies:
      build_runner: 2.5.4
      mocktail: 1.0.2
  clean:
    hooks:
      post: |
        melos exec --flutter --concurrency=3 -- "flutter clean"
        melos run build:clean

scripts:
  analyze: dart format . --set-exit-if-changed && flutter analyze --fatal-infos .

  cache_clean:
    run: dart run tools/cache_clean_and_melos_bs.dart
    description: Clean pub cache and run melos bootstrap

  build-core:
    run: melos exec -- "dart run build_runner build -d"
    description: "Generate core"
    packageFilters:
      scope: "*core*"

  build:
    run: melos run build:select --no-select
    description: "Run build runner in all packages that depend on it."

  build:clean:
    run: melos run build:clean:select --no-select
    description: "Run build runner clean in all packages that depend on it."

  build:select:
    run: melos exec -- "dart run build_runner build -d"
    description: "Run build runner in selected package that depends on build_runner."
    packageFilters:
      ignore:
        - "*core*"
      dependsOn:
        - "build_runner"

  build:clean:select:
    run: melos exec -- "dart run build_runner clean"
    description: "Run build runner clean in selected package that depends on build_runner."
    packageFilters:
      dependsOn:
        - "build_runner"

  initialize-app:
    run: |
      melos run build
      melos run build-core
    description: Initialize App.
