name: fintechapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: 3.6.0
# --------- DEPENDENCIES ---------
dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: 5.6.7
  cupertino_icons: 1.0.8
  firebase_auth: 5.5.3
  firebase_core: 3.13.0
  flutter_riverpod: 2.6.1
  flutter_screenutil: 5.9.3
  flutter_svg: 2.0.17
  go_router: 15.1.2
  google_sign_in: 6.3.0
  intl: 0.20.2
  miny_design_system:
    git:
      url: https://github.com/blackminystudio/miny-design-system.git
      ref: main
  pin_code_fields: 8.0.1
  iconsax: 0.0.8

# --------- DEV DEPENDENCIES ---------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

