name: core
description: "Core package for DI, routing, theming & shared utilities."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  # Features
  auth:
    path: ../features/auth
  home:
    path: ../features/home

  get_it: ^8.0.3
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.13.0
  auto_route: ^6.0.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation for AutoRoute
  build_runner: any
  auto_route_generator: any
