name: config
description: "config package for DI, routing, & feature level configurations"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  onboarding:
    path: ../features/onboarding
  flutter:
    sdk: flutter

  # Internal Packages
  core:
    path: ../core
  auth:
    path: ../features/auth
  home:
    path: ../features/home

  # External Packages
  auto_route: 10.1.0
  dartz: 0.10.1
  device_info_plus: 11.5.0
  equatable: 2.0.7
  firebase_auth: 6.0.0
  firebase_core: 4.0.0
  flutter_native_splash: 2.4.4
  flutter_riverpod: 2.6.1
  flutter_screenutil: 5.9.3
  flutter_secure_storage: 9.2.4
  get_it: 8.0.3
  injectable: 2.5.0
  intl: 0.20.2
  json_annotation: 4.9.0
  logger: 2.6.0
  package_info_plus: 8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # External dev dependencies
  auto_route_generator: 10.2.3
  build_runner: 2.5.4
  injectable_generator: 2.7.0
  mocktail: 1.0.2
