name: auth
description: Authentication feature
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  # Internal Packages
  core:
    path: ../../core

  # External Packages
  firebase_auth: 6.0.0
  flutter_svg: 2.2.0
  google_sign_in: 6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # External dev dependencies
  auto_route_generator: 10.2.3
  build_runner: 2.5.4
  injectable_generator: 2.7.0

  # Mock dependencies
  mocktail: 1.0.2
  firebase_auth_mocks: 0.15.0
  google_sign_in_mocks: 0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
