# .github/workflows/flutter_ci.yml
name: Flutter CI

on:
  push:
    branches:
      - staging*
  pull_request:
    branches:
      - "**"

    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    name: Lint
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Check for caret symbol (^) in all pubspec.yaml files
        run: |
          # Ensure we are in the root directory of the project
          cd $(git rev-parse --show-toplevel)

          # Find all pubspec.yaml files and search for caret symbol
          has_caret=$(find . -name "pubspec.yaml" -exec grep -H -E "^\s*[a-zA-Z0-9_]+:\s*\^" {} + || true)
          if [[ -n "$has_caret" ]]; then
            echo "Error: Found caret symbol (^) in the following pubspec.yaml files:"
            echo "$has_caret"
            exit 1
          else
            echo "No caret symbols found in pubspec.yaml files. All checks passed."
          fi
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: stable
          cache: true
      - name: Set up Melos
        run: dart pub global activate melos

      - name: Bootstrap Melos
        run: melos exec --diff=origin/${{github.base_ref}} --flutter -- flutter pub get && melos exec --diff=origin/${{ github.base_ref }} --no-flutter -- dart pub get
      - name: List Cyclic Dependency
        run: melos list --cycles

      - name: Run tests with coverage
        run: melos run gen_coverage

      - name: Dart Format
        run: dart format . --set-exit-if-changed
      - name: Get Affected Packages
        id: affected_packages
        run: |
          AFFECTED_PACKAGES=$(./.github/scripts/changed_packages.sh ${{ github.base_ref }})
          echo "affected_packages=$AFFECTED_PACKAGES" >> $GITHUB_ENV
        env:
          GITHUB_ENV: $GITHUB_ENV

      - name: Dart Analyze (only affected packages)
        run: |
          AFFECTED_PACKAGES="${{env.affected_packages}}"
          
          if [ "$AFFECTED_PACKAGES" = "NO_CHANGES" ]; then
            echo "No Dart packages affected. Skipping analysis."
            exit 0
          fi
          
          echo "Running analysis in the following packages:"
          echo "$AFFECTED_PACKAGES"
          
          for pkg_path in $AFFECTED_PACKAGES; do
            package_name=$(basename "$pkg_path")
            echo "Analyzing $package_name ($pkg_path)"
            melos exec --scope="$package_name" -- flutter analyze --fatal-infos .
          done

